version: '3'
# Define services
services:
    rstudio:
        container_name: rStudio_docker
        volumes:
            - ./rStudioDocker:/home/david/
        build:
            context: rStudioDocker
            dockerfile: Dockerfile
        ports:
            - "8787:8787"
        environment:
            - USER=david
            - PASSWORD=david
